const GET_COUNTRIES = 'GET_COUNTRIES';
const GET_COUNTRY = 'GET_COUNTRY';
const CLEAN_COUNTRY = 'CLEAN_COUNTRY';
const CLEAN_COUNTRIES = 'CLEAN_COUNTRIES';

export { GET_COUNTRY, GET_COUNTRIES, CLEAN_COUNTRY, CLEAN_COUNTRIES };
